doc: zh_CN version of dataframes_load_save.md
JuliaCN/JuliaDataScience pull request #1
Opened 2021-11-09 06:45 UTC by guixinliu

Hello, @findmyway.

 I am a Physics student at Northwest University. 

I am a Julia beginner. I have read through the manual part and some standard libraries of Julia documentation. Now I have mastered the basic usage of Julia, and some design pattern implemented by multiple dispatch.

 I hope that this draft may be helpful.

2021-11-10 02:41 UTC, findmyway commented
直接覆盖下 `contents` 下的文件？

（抱歉昨天比较忙没来得及review）

2021-11-10 13:42 UTC, guixinliu commented
好的，已经改为直接覆盖了。

2021-11-11 03:04 UTC, findmyway requested changes
还可以，但是有些长句需要你自己再斟酌下

2021-11-11 03:04 UTC, findmyway commented on contents/dataframes_load_save.md
> +仅在 Julia 程序中使用数据而不能加载或保存数据是非常局限的。
```suggestion
仅在 Julia 程序中使用数据非常有局限性，通常还需要加载或保存数据。
```

2021-11-11 03:04 UTC, findmyway commented on contents/dataframes_load_save.md
> +因此，我们开始讨论如何存储文件到硬盘和从硬盘读取文件。
中文翻译里减少不必要的 “我们”， 其它地方也是如此

2021-11-11 03:04 UTC, findmyway commented on contents/dataframes_load_save.md
> +因此，我们开始讨论如何存储文件到硬盘和从硬盘读取文件。
```suggestion
因此，本节主要讨论如何存储数据到硬盘和从硬盘读取数据文件。
```

2021-11-11 03:04 UTC, findmyway commented on contents/dataframes_load_save.md
> +我们关注 CSV 和 Excel 文件格式，分别参见 @sec:csv 和 @sec:excel，因为这些是表格数据最常见的数据格式。
```suggestion
这里我们重点关注 CSV 和 Excel 这两类最常见数据文件格式，分别参见 @sec:csv 和 @sec:excel。
```

2021-11-11 03:04 UTC, findmyway commented on contents/dataframes_load_save.md
> +CSV 文件相比其他数据存储文件有两点优势。首先，它准确实现了名称所对应的功能，即在存储值时使用逗号`,`分隔。此首字母缩写词也用作其文件扩展名。因此，请确保使用“.csv”扩展名（例如“myfile.csv”）保存文件。为了演示 CSV 文件的结构，我们安装 [`CSV.jl`](http://csv.juliadata.org/latest/) 包：
> 它准确实现了名称所对应的功能，即在存储值时使用逗号`,`分隔

呃，不是很通顺

2021-11-11 03:04 UTC, findmyway commented on contents/dataframes_load_save.md
> +该格式假设数据不包含制表符，这在大多数情况下成立。
```suggestion
该格式假设数据不包含制表符，这一点在大多数情况下是成立的。
```

2021-11-11 03:04 UTC, findmyway commented on contents/dataframes_load_save.md
> +## 加载和保存文件 {#sec: load_save}
```suggestion
## 加载和保存文件 {#sec:load_save}
```

2021-11-13 03:02 UTC, guixinliu commented on contents/dataframes_load_save.md
> +仅在 Julia 程序中使用数据而不能加载或保存数据是非常局限的。
已修改。

2021-11-13 03:03 UTC, guixinliu commented on contents/dataframes_load_save.md
> +因此，我们开始讨论如何存储文件到硬盘和从硬盘读取文件。
已尽可能减少“我们”

2021-11-13 03:04 UTC, guixinliu commented on contents/dataframes_load_save.md
> +该格式假设数据不包含制表符，这在大多数情况下成立。
已修改。

2021-11-13 03:06 UTC, guixinliu commented on contents/dataframes_load_save.md
> +CSV 文件相比其他数据存储文件有两点优势。首先，它准确实现了名称所对应的功能，即在存储值时使用逗号`,`分隔。此首字母缩写词也用作其文件扩展名。因此，请确保使用“.csv”扩展名（例如“myfile.csv”）保存文件。为了演示 CSV 文件的结构，我们安装 [`CSV.jl`](http://csv.juliadata.org/latest/) 包：
这里确实不太合适。 我已修改。

由于翻译经验不够多，技术上有所欠缺，还烦请您费心指导。

2021-11-13 04:29 UTC, findmyway approved these changes

2021-11-13 04:29 UTC, findmyway commented on contents/dataframes_load_save.md
> +第二个好处是，`XLSX.jl` 是用纯 Julia 编写的，这使得可以轻松地检查和理解指令背后发生的事情。
```suggestion
另外一个优点是，`XLSX.jl` 是用纯 Julia 编写的，这使得可以轻松地检查和理解指令背后发生的事情。
```

2021-11-13 04:30 UTC, merged

2021-11-13 04:59 UTC, findmyway commented on contents/dataframes_load_save.md
> +这很有效，但是如果我们的数据 ** 包含逗号 `,`** 作为值怎么办？
@guixinliu 这个地方的加组没有高亮出来，应该是空格的 原因，https://cn.julialang.org/JuliaDataScience/load_save#sec:csv

![image](https://user-images.githubusercontent.com/5612003/141606274-e3dc9873-ce05-4e0a-a64e-904bd82f386a.png)

2021-11-13 05:25 UTC, guixinliu commented on contents/dataframes_load_save.md
> +这很有效，但是如果我们的数据 ** 包含逗号 `,`** 作为值怎么办？
是的，“包含”前面多了空格

2021-11-13 05:38 UTC, findmyway commented on contents/dataframes_load_save.md
> +这很有效，但是如果我们的数据 ** 包含逗号 `,`** 作为值怎么办？
再发个PR fix下？

2021-11-13 05:43 UTC, guixinliu commented on contents/dataframes_load_save.md
> +这很有效，但是如果我们的数据 ** 包含逗号 `,`** 作为值怎么办？
是的。我刚在确认有无类似情况。