Add Flags Button to `CN` Version
JuliaCN/JuliaDataScience pull request #37
Opened 2022-01-28 18:14 UTC by storopoli

This PR adds the flags to `CN` `index.md`.

2022-01-28 18:33 UTC, rikhuijzer commented on contents/index.md
> +<a href="/"><button>🇨🇳</botton></a>
```suggestion
<a href="https://cn.julialang.org/JuliaDataScience/"><button>🇨🇳</botton></a>
```

2022-01-28 18:37 UTC, storopoli commented
Tagging @findmyway because neither @rikhuijzer nor me have merge privileges 😂

2022-01-29 01:41 UTC, guixinliu commented on contents/index.md
> +</di
````suggestion
</div>
```
````

2022-01-29 01:47 UTC, guixinliu requested changes
The `<div>` tag at 17th line and three quotes  ` ``` ` at  3rd line should be closed.

2022-01-29 01:47 UTC, guixinliu commented on contents/index.md
> +</di
````suggestion
</div>
```
````

2022-01-29 02:23 UTC, guixinliu commented
Thank you @rikhuijzer  and @storopoli !

2022-01-29 02:23 UTC, merged

2022-01-29 10:54 UTC, storopoli commented
Thank you!